standalone_role: /home/stack/StandaloneEdge.yaml
hostname: dcn-edge1
standalone_host: dcn-edge1.macchi.pro
public_api: 10.46.26.15
control_plane_ip: 10.46.26.15
neutron_bridge_mappings: "external:br-ex,segment0:br-segment0"
enabled_services:
  - /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml
  - /home/stack/edge1.yaml
  - /home/stack/export_control_plane/passwords.yaml
  - /home/stack/export_control_plane/oslo.yaml
  - /home/stack/export_control_plane/endpoint-map.json
  - /home/stack/export_control_plane/extra-host-file-entries.json
  - /home/stack/export_control_plane/all-nodes-extra-map-data.json
